# Generated by Django 4.2.5 on 2023-09-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_telegram_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telegram_username',
            new_name='telegram_id',
        ),
    ]
