# Generated by Django 4.2.5 on 2023-09-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_telegram_username_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='id пользователя в Telegram'),
        ),
    ]
