# Generated by Django 4.2.5 on 2023-09-22 08:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atomic_habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='is_pleasant_habit',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='признак приятной привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='признак публичности'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_related_habit',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='признак связанной привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='периодичность в днях'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.PositiveSmallIntegerField(blank=True, default=60, null=True, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='время на выполнение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit', to=settings.AUTH_USER_MODEL, verbose_name='создатель привычки'),
        ),
    ]
