# Generated by Django 4.2.5 on 2023-09-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomic_habits', '0002_alter_habit_is_pleasant_habit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='award',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='награда'),
        ),
    ]
