# Generated by Django 4.2.5 on 2023-09-22 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atomic_habits', '0003_alter_habit_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atomic_habits.habit', verbose_name='связанная привычка'),
        ),
    ]
