# Generated by Django 4.2.5 on 2023-09-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomic_habits', '0007_alter_habit_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время и дата начала'),
        ),
    ]
