# Generated by Django 4.2.5 on 2023-09-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomic_habits', '0008_alter_habit_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.DateTimeField(verbose_name='время и дата старта'),
        ),
    ]
